### ISSUE TITLE
No file found 'custom_components/airdog_miio_airpurifier/manifest.json'

### ISSUE THREAD

**Issue by Laxilef** [artem-sedykh/airdog_airpurifier#1]
Здравствуйте.
Пытаюсь интегрировать airdog.airpurifier.x5 в HA, нашел вашу интеграцию, но отсутствует манифест.
Вопрос в следующем: актуальна ли интеграция и, если да, то не могли бы вы добавить манифест?
Благодарю!

**Comment by artem-sedykh** [comment]
Привет! вышла новая версия HA, они там переделали компонент fan, так что нужно отрефакторить код, думаю на выходных будет время это сделать.

**Comment by Laxilef** [comment]
Спасибо, буду ждать.

p.s. Вы не хотите добавить свою интеграцию в офф. репозиторий HA или в syssi/xiaomi_airpurifier?

**Comment by artem-sedykh** [comment]
В syssi/xiaomi_airpurifier у же добавили [PR](https://github.com/syssi/xiaomi_airpurifier/pull/159) так что скоро будет.
